module.exports = [
  {
    id: "challenge-5k",
    label: "5K Challenge",
    accountSize: 5000,
    price: 4999,
    currency: "INR",
    profitTarget: 8,
    maxDrawdown: 10,
    dailyLoss: 5,
  },
  {
    id: "challenge-10k",
    label: "10K Challenge",
    accountSize: 10000,
    price: 7999,
    currency: "INR",
    profitTarget: 8,
    maxDrawdown: 10,
    dailyLoss: 5,
  },
  {
    id: "challenge-25k",
    label: "25K Challenge",
    accountSize: 25000,
    price: 14999,
    currency: "INR",
    profitTarget: 8,
    maxDrawdown: 10,
    dailyLoss: 5,
  },
];
